# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sensor_data_pb2 as sensor__data__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sensor_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SensorDataServiceStub(object):
    """gRPC 双向流服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSensorData = channel.stream_stream(
                '/com.continuousauth.proto.SensorDataService/StreamSensorData',
                request_serializer=sensor__data__pb2.DataPacket.SerializeToString,
                response_deserializer=sensor__data__pb2.ServerDirective.FromString,
                _registered_method=True)
        self.GetInitialPolicy = channel.unary_unary(
                '/com.continuousauth.proto.SensorDataService/GetInitialPolicy',
                request_serializer=sensor__data__pb2.PolicyRequest.SerializeToString,
                response_deserializer=sensor__data__pb2.PolicyUpdate.FromString,
                _registered_method=True)
        self.StartAuthentication = channel.unary_unary(
                '/com.continuousauth.proto.SensorDataService/StartAuthentication',
                request_serializer=sensor__data__pb2.AuthSessionRequest.SerializeToString,
                response_deserializer=sensor__data__pb2.AuthSessionResponse.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/com.continuousauth.proto.SensorDataService/SendHeartbeat',
                request_serializer=sensor__data__pb2.Heartbeat.SerializeToString,
                response_deserializer=sensor__data__pb2.HeartbeatAck.FromString,
                _registered_method=True)
        self.ReportMetrics = channel.unary_unary(
                '/com.continuousauth.proto.SensorDataService/ReportMetrics',
                request_serializer=sensor__data__pb2.MetricsReport.SerializeToString,
                response_deserializer=sensor__data__pb2.MetricsResponse.FromString,
                _registered_method=True)


class SensorDataServiceServicer(object):
    """gRPC 双向流服务定义
    """

    def StreamSensorData(self, request_iterator, context):
        """双向流RPC：客户端发送DataPacket，服务器返回ServerDirective
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInitialPolicy(self, request, context):
        """单向RPC：获取初始策略配置
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartAuthentication(self, request, context):
        """单向RPC：开始认证会话
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """单向RPC：心跳检测
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportMetrics(self, request, context):
        """单向RPC：上报聚合指标
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSensorData': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSensorData,
                    request_deserializer=sensor__data__pb2.DataPacket.FromString,
                    response_serializer=sensor__data__pb2.ServerDirective.SerializeToString,
            ),
            'GetInitialPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInitialPolicy,
                    request_deserializer=sensor__data__pb2.PolicyRequest.FromString,
                    response_serializer=sensor__data__pb2.PolicyUpdate.SerializeToString,
            ),
            'StartAuthentication': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAuthentication,
                    request_deserializer=sensor__data__pb2.AuthSessionRequest.FromString,
                    response_serializer=sensor__data__pb2.AuthSessionResponse.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=sensor__data__pb2.Heartbeat.FromString,
                    response_serializer=sensor__data__pb2.HeartbeatAck.SerializeToString,
            ),
            'ReportMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportMetrics,
                    request_deserializer=sensor__data__pb2.MetricsReport.FromString,
                    response_serializer=sensor__data__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.continuousauth.proto.SensorDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.continuousauth.proto.SensorDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SensorDataService(object):
    """gRPC 双向流服务定义
    """

    @staticmethod
    def StreamSensorData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/com.continuousauth.proto.SensorDataService/StreamSensorData',
            sensor__data__pb2.DataPacket.SerializeToString,
            sensor__data__pb2.ServerDirective.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInitialPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.continuousauth.proto.SensorDataService/GetInitialPolicy',
            sensor__data__pb2.PolicyRequest.SerializeToString,
            sensor__data__pb2.PolicyUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartAuthentication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.continuousauth.proto.SensorDataService/StartAuthentication',
            sensor__data__pb2.AuthSessionRequest.SerializeToString,
            sensor__data__pb2.AuthSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.continuousauth.proto.SensorDataService/SendHeartbeat',
            sensor__data__pb2.Heartbeat.SerializeToString,
            sensor__data__pb2.HeartbeatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.continuousauth.proto.SensorDataService/ReportMetrics',
            sensor__data__pb2.MetricsReport.SerializeToString,
            sensor__data__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
